### ISSUE TITLE
Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by demiters** [imgix/p12ToPem#1]
I am using this in Meteor and get an error trying to export from my p12 certificate (the password is correct and the certificate is valid):

```
TypeError: Cannot read property 'key' of undefined
W20151210-04:12:41.549(2)? (STDERR)     at p12ToPem (/home/arturs/git/project/.meteor/local/isopacks/npm-container/npm/node_modules/p12-to-pem/p12ToPem.js:23:74)
W20151210-04:12:41.549(2)? (STDERR)     at [object Object].getSignature (server/payments.js:35:22)
W20151210-04:12:41.549(2)? (STDERR)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
W20151210-04:12:41.549(2)? (STDERR)     at livedata_server.js:1611:18
W20151210-04:12:41.549(2)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
W20151210-04:12:41.549(2)? (STDERR)     at [object Object]._.extend.apply (livedata_server.js:1610:45)
W20151210-04:12:41.549(2)? (STDERR)     at [object Object]._.extend.call (livedata_server.js:1553:17)
W20151210-04:12:41.550(2)? (STDERR)     at server/payments.js:2:10
W20151210-04:12:41.550(2)? (STDERR)     at /home/arturs/git/project/.meteor/local/build/programs/server/boot.js:249:5
```

**Comment by Mr0grog** [comment]
Are you able to generate another certificate that doesn’t work? Is it possible for you to generate one that you can share?

**Comment by demiters** [comment]
Turns out the private key within my certificate was called something other than 'privatekey' so I had to change that in p12ToPem.js. Is that unusual? I'd propose adding a third, optional parameter to p12ToPem() which would be string override for 'privatekey' in case it isn't found.

**Comment by Mr0grog** [comment]
Hmmm, I’m definitely not an expert on PKCS12 or certificates in general, but I believe that is unusual. Would it have been helpful or useful to have the ability to specify key bag’s name as an optional argument?
